version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: nest_clean_mongo
    restart: always
    ports:
      - "27017:27017"
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip_all &
        sleep 5 &&
        mongosh --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"localhost:27017\" }]})' ||
        echo 'Replica set may already be initialized'
        && tail -f /dev/null
      "
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
