version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: nest_clean_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: productsdb
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
